language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - "yarn run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: process.env.REACT_APP_GITHUB_TOKEN
  local_dir: dist
  edge: true
  on:
    branch: master
